name: Update README file count

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Inst Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Running sprypt
        run: python count_files.py

      - name: Коміт змін
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README" || exit 0
          git push
